###PO Create
POST http://localhost:4004/pocreation/POCreate
Content-Type: application/json

{   
    "input":"{\"PO_Header\":[{\"PO_Number\":1,\"CreationDate\":\"2023-09-26\",\"DeliveryDate\":\"2023-10-26\",\"Status\":1,\"CreatedBy\":\"CDAN\",\"PCode\":\"W010\",\"CompanyCode\":\"ASP\"}],\"PO_Item\":[{\"PO_Item_Num\":1,\"PO_Number\":1,\"MCode\":\"DUMMYENGR28WBRN\",\"Quantity\":4,\"Amount\":0},{\"PO_Item_Num\":1,\"PO_Number\":1,\"MCode\":\"DSG1414EB\",\"Quantity\":5,\"Amount\":0}],\"PO_Event\":[{\"PO_Number\":1,\"EVENT_CODE\":1,\"EVENT_DESCRIPTION\":\"Created\",\"EVENT_DATE\":\"2023-09-26T06:49:03.231Z\",\"EVENT_BY\":\"CDAN\"}]}"
}

###PO Approve
POST http://localhost:4004/poapproval/POApprove
Content-Type: application/json

{
    "input":"{\"PO_Number\":10007,\"PO_Events\":{\"EVENT_DESCRIPTION\":\"Purchase Order Approved\",\"EVENT_BY\":\"MR_APPROVER\"}}"
}


###PO Complete
POST http://localhost:4004/poapproval/POComplete
Content-Type: application/json

{
    "input":"{\"PO_Number\":10004,\"PO_Events\":{\"EVENT_DESCRIPTION\":\"Purchase Order Completed\",\"EVENT_BY\":\"MR_APPROVER2\"}}"
}


###PO Reject
POST http://localhost:4004/poapproval/POReject
Content-Type: application/json

{
    "input":"{\"PO_Number\":10006,\"PO_Events\":{\"EVENT_DESCRIPTION\":\"Purchase Order Rejected\",\"EVENT_BY\":\"MR_APPROVER\"}}"
}

###PO Cancelled        
GET http://localhost:4004/poreport/POCancelled()

###POST ONLY HEADER
POST http://localhost:4004/pocreation/POHeader
Content-Type: application/json

{
    "PO_Number":10001,
    "CreationDate":"2023-09-26",
    "DeliveryDate":"2023-10-26",
    "Status":1,
    "CreatedBy":"CDAN",
    "PCode":"W010",
    "CompanyCode":"ASP"
}

##create poitem
POST http://localhost:4004/pocreation/POItem
Content-Type: application/json

{
    "PO_Item_Num":1,
    "PO_Number":1,
    "MCode":"DUMMYENGR28WBRN",
    "Quantity":4,
    "Amount":0
}

###SEND PAYLOAD   
POST http://localhost:4004/pocreation/POHeader
Content-Type: application/json

{
    "PO_Number": 10007, 
    "CreationDate": "2023-10-18",
    "DeliveryDate": "2023-11-18",
    "Status": 5, 
    "MadeBy": "CDAN", 
    "PCode": "W010", 
    "CompanyCode": "ASP", 
    "Delete": "",    
    "Criticality":0,
    "PO_Item_Master":[],
    "PO_Attach_Master":[{
        "PO_Number": 10007, 
        "File_Type": "image/png",
		"FileName": "Dummy",
		"Size": 1234          
    }]        
}   

###SEND ATTACH PAYLOAD
POST http://localhost:4004/pocreation/PO_Attachment
Content-Type: application/json    

{  
    "PO_Number": 10002,   
    "File_Type":"",
    "FileName":"",
    "MimeType":"",   
    "FileChk":"",
    "Size":123,
    "FileURL":""
}